# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TongTianLu.TongTopStore
PackageVersion: 0.7.1
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-10-03
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hencter/tongtop-store/releases/download/v0.7.1/tongtop-store_0.7.1_x64-setup.exe
    InstallerSha256: 7E91A3FFF5E6FB968B97874F9AF49AD24DD9AB08832344CD0FE7B6E57F891543
    AppsAndFeaturesEntries:
      - DisplayName: tongtop-store
        Publisher: tongtianlu
        InstallerType: nullsoft
ManifestType: installer
ManifestVersion: 1.12.0
