# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TongTianLu.TongTopStore
PackageVersion: 0.6.7
InstallerType: nullsoft
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-23
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/hencter/tongtop-store/releases/download/v0.6.7/tongtop-store_0.6.7_x64-setup.exe
    InstallerSha256: 679F4927881E0868278E80C6EEFBCFC0B60AC1B171C801D3031A49E13111D24D
    AppsAndFeaturesEntries:
      - DisplayName: tongtop-store
        Publisher: tongtianlu
        InstallerType: nullsoft
ManifestType: installer
ManifestVersion: 1.12.0
